[build]
  publish = "/"
  command = "node build.js"

[context.production]
  environment = { NODE_VERSION = "14" }

[context.production.environment]
  # 这里可以设置默认的环境变量
  BASE_URL = "https://api.example.com"
